name: Build

on:
  push:
    branches: ["main", "dev"]

jobs:
  build:
    name: Check and build package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install and configure Poetry
      uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b
    - name: Install dependencies
      run: poetry install
    - name: Analysing code with pylint
      run: poetry run pylint .
    - name: Test with pytest
      run: poetry run pytest
    - name: Build poetry package
      run: poetry build
