name: Release

on:
  push:
    tags:
      - v2.*

jobs:
  build:
    name: Check and build package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
    - name: Set up Python
      uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566
      with:
        python-version: 3.11
    - name: Install and configure Poetry
      uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b
    - name: Install dependencies
      run: poetry install
    - name: Analysing code with pylint
      run: poetry run pylint .
    - name: Test with pytest
      run: poetry run pytest
    - name: Build poetry package
      run: poetry build
    - name: Store the distribution packages
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish Python package to PyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/imagecolor
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e

  github-release:
    name: Sign the Python package with Sigstore and upload them to GitHub Release
    needs:
    - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@e323e1b02e26cc6600843935562c862b94200b0c
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ github.ref_name }}'
        --repo '${{ github.repository }}'
        --notes ""
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/**
        --repo '${{ github.repository }}'

  publish-to-testpypi:
    name: Publish Python package to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: dev
      url: https://test.pypi.org/p/imagecolor

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
      with:
        repository-url: https://test.pypi.org/legacy/
